## dinshi.yml
name: 'dingshiqi'
 
on:
  schedule:
    - cron: '25 3 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install bs4          
          pip install numpy
      - name: Install dependencies
        run: 
          python ji.py
